/* ------------------------------------------------------------------------ */
/* ----------------------- ingestion_column_details ----------------------- */
/* ------------------------------------------------------------------------ */

DROP TABLE IF EXISTS `dw-metadata-utilities.metadata_utilities.ingestion_column_details`;
CREATE TABLE IF NOT EXISTS `dw-metadata-utilities.metadata_utilities.ingestion_column_details` (
  column_name STRING NOT NULL, --ID
  datatype STRING NOT NULL, --STRING
  ordinal_position INT64 NOT NULL, --1
  mapping_column STRING, --ID
  source_system STRING NOT NULL, --COINCAP
  project_id STRING NOT NULL,
  dataset STRING NOT NULL, --COINCAP-DATA-HUB
  table_name STRING NOT NULL, --STG_COINCAP_ASSETS
  modified_by STRING NOT NULL, --ADMIN
  modified_date DATETIME  NOT NULL, --CURRENT_DATETIME
  created_by STRING NOT NULL, --ADMIN
  created_date DATETIME NOT NULL --CURRENT_DATETIME 
);



INSERT INTO `dw-metadata-utilities.metadata_utilities.ingestion_column_details` 
(column_name,datatype,ordinal_position,mapping_column,source_system, project_id, dataset,table_name,modified_by,modified_date,created_by,created_date) VALUES
   ('ID','STRING',1,'ID','COINCAP','COINCAP-DATA-HUB','COINCAP_DATA','COINCAP_ASSETS','ADMIN',CURRENT_DATETIME,'ADMIN',CURRENT_DATETIME),
   ('RANK','INT64',2,'RANK','COINCAP','COINCAP-DATA-HUB','COINCAP_DATA','COINCAP_ASSETS','ADMIN',CURRENT_DATETIME,'ADMIN',CURRENT_DATETIME),
   ('NAME','STRING',3,'NAME','COINCAP','COINCAP-DATA-HUB','COINCAP_DATA','COINCAP_ASSETS','ADMIN',CURRENT_DATETIME,'ADMIN',CURRENT_DATETIME),
   ('SUPPLY','FLOAT64',4,'SUPPLY','COINCAP','COINCAP-DATA-HUB','COINCAP_DATA','COINCAP_ASSETS','ADMIN',CURRENT_DATETIME,'ADMIN',CURRENT_DATETIME),
   ('MAXSUPPLY','FLOAT64',5,'MAXSUPPLY','COINCAP','COINCAP-DATA-HUB','COINCAP_DATA','COINCAP_ASSETS','ADMIN',CURRENT_DATETIME,'ADMIN',CURRENT_DATETIME),
   ('VOLUMEUSD24HR','FLOAT64',6,'VOLUME_USD_24HR','COINCAP','COINCAP-DATA-HUB','COINCAP_DATA','COINCAP_ASSETS','ADMIN',CURRENT_DATETIME,'ADMIN',CURRENT_DATETIME),
   ('PRICEUSD','FLOAT64',7,'PRICE_USD','COINCAP','COINCAP-DATA-HUB','COINCAP_DATA','COINCAP_ASSETS','ADMIN',CURRENT_DATETIME,'ADMIN',CURRENT_DATETIME),
   ('CHANGEPERCENT24HR','FLOAT64',8,'CHANGE_PERCENT_24HR','COINCAP','COINCAP_DATA','COINCAP-DATA-HUB','COINCAP_ASSETS','ADMIN',CURRENT_DATETIME,'ADMIN',CURRENT_DATETIME),
   ('VWAP24HR','FLOAT64',9,'VWAP_24HR','COINCAP','COINCAP-DATA-HUB','COINCAP_DATA','COINCAP_ASSETS','ADMIN',CURRENT_DATETIME,'ADMIN',CURRENT_DATETIME),
   ('EXPLORER','STRING',10,'EXPLORER','COINCAP','COINCAP-DATA-HUB','COINCAP_DATA','COINCAP_ASSETS','ADMIN',CURRENT_DATETIME,'ADMIN',CURRENT_DATETIME);


INSERT INTO `dw-metadata-utilities.metadata_utilities.ingestion_column_details` 
(column_name,datatype,ordinal_position,mapping_column,source_system, project_id, dataset,table_name,modified_by,modified_date,created_by,created_date) VALUES
   ('ID','STRING',1,'ID','COINCAP','COINCAP-DATA-HUB','COINCAP_DATA','COINCAP_RATES','ADMIN',CURRENT_DATETIME,'ADMIN',CURRENT_DATETIME),
   ('SYMBOL','STRING',2,'SYMBOL','COINCAP','COINCAP-DATA-HUB','COINCAP_DATA','COINCAP_RATES','ADMIN',CURRENT_DATETIME,'ADMIN',CURRENT_DATETIME),
   ('CURRENCYSYMBOL','STRING',3,'CURRENCY_SYMBOL','COINCAP','COINCAP-DATA-HUB','COINCAP_DATA','COINCAP_RATES','ADMIN',CURRENT_DATETIME,'ADMIN',CURRENT_DATETIME),
   ('TYPE','STRING',4,'TYPE','COINCAP','COINCAP-DATA-HUB','COINCAP_DATA','COINCAP_RATES','ADMIN',CURRENT_DATETIME,'ADMIN',CURRENT_DATETIME),
   ('RATEUSD','FLOAT64',5,'RATE_USD','COINCAP','COINCAP-DATA-HUB','COINCAP_DATA','COINCAP_RATES','ADMIN',CURRENT_DATETIME,'ADMIN',CURRENT_DATETIME)
   ;

INSERT INTO `dw-metadata-utilities.metadata_utilities.ingestion_column_details` 
(column_name,datatype,ordinal_position,mapping_column,source_system, project_id, dataset,table_name,modified_by,modified_date,created_by,created_date) VALUES
   ('EXCHANGEID','STRING',1,'EXCHANGE_ID','COINCAP','COINCAP-DATA-HUB','COINCAP_EXCHANGES','COINCAP_RATES','ADMIN',CURRENT_DATETIME,'ADMIN',CURRENT_DATETIME),
   ('NAME','STRING',2,'NAME','COINCAP','COINCAP-DATA-HUB','COINCAP_DATA','COINCAP_EXCHANGES','ADMIN',CURRENT_DATETIME,'ADMIN',CURRENT_DATETIME),
   ('RANK','INT64',3,'RANK','COINCAP','COINCAP-DATA-HUB','COINCAP_DATA','COINCAP_EXCHANGES','ADMIN',CURRENT_DATETIME,'ADMIN',CURRENT_DATETIME),
   ('PERCENTTOTALVOLUME','FLOAT64',4,'PERCENT_TOTAL_VOLUME','COINCAP','COINCAP-DATA-HUB','COINCAP_DATA','COINCAP_EXCHANGES','ADMIN',CURRENT_DATETIME,'ADMIN',CURRENT_DATETIME),
   ('VOLUMEUSD','FLOAT64',5,'VOLUME_USD','COINCAP','COINCAP-DATA-HUB','COINCAP_DATA','COINCAP_EXCHANGES','ADMIN',CURRENT_DATETIME,'ADMIN',CURRENT_DATETIME),
   ('TRADINGPAIRS','INT64',6,'TRADING_PAIRS','COINCAP','COINCAP-DATA-HUB','COINCAP_DATA','COINCAP_EXCHANGES','ADMIN',CURRENT_DATETIME,'ADMIN',CURRENT_DATETIME),
   ('SOCKET','STRING',7,'SOCKET','COINCAP','COINCAP-DATA-HUB','COINCAP_DATA','COINCAP_EXCHANGES','ADMIN',CURRENT_DATETIME,'ADMIN',CURRENT_DATETIME),
   ('EXCHANGEURL','STRING',8,'EXCHANGE_URL','COINCAP','COINCAP-DATA-HUB','COINCAP_DATA','COINCAP_EXCHANGES','ADMIN',CURRENT_DATETIME,'ADMIN',CURRENT_DATETIME),
   ('UPDATED','INT64',9,'UPDATED','COINCAP','COINCAP-DATA-HUB','COINCAP_DATA','COINCAP_EXCHANGES','ADMIN',CURRENT_DATETIME,'ADMIN',CURRENT_DATETIME)
   ;   
